# Generated by Django 3.2 on 2021-05-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': ('Product',), 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='order_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Times Ordered'),
        ),
    ]
