# Generated by Django 3.2 on 2021-05-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_count',
            field=models.FloatField(default=0, verbose_name='Number of Times Ordered'),
        ),
    ]
