# Generated by Django 3.2 on 2021-05-13 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_order_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Times Ordered'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Average Rating'),
        ),
    ]
