# Generated by Django 3.2 on 2021-05-13 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, editable=False, verbose_name='Created at')),
                ('modified', models.DateTimeField(db_index=True, verbose_name='Last modified')),
                ('hidden', models.BooleanField(db_index=True, default=False, verbose_name='Hidden or deleted')),
                ('address', models.CharField(max_length=200, verbose_name='Delivery Address')),
                ('status', models.CharField(choices=[('Waiting for Payment', 'Waiting for Payment'), ('Confirmed', 'Confirmed'), ('Processed', 'Processed'), ('Delivered', 'Delivered')], default='Waiting for Payment', max_length=50, verbose_name='Status')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Original Price')),
                ('discounted_price', models.FloatField(blank=True, null=True, verbose_name='Price with Discount')),
                ('delivery_price', models.FloatField(blank=True, null=True, verbose_name='Delivery Price')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='Total Price')),
                ('cashback', models.FloatField(blank=True, null=True, verbose_name='Cashback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, editable=False, verbose_name='Created at')),
                ('modified', models.DateTimeField(db_index=True, verbose_name='Last modified')),
                ('hidden', models.BooleanField(db_index=True, default=False, verbose_name='Hidden or deleted')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price', models.PositiveIntegerField(verbose_name='Original Price')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='Discount')),
                ('total_price', models.FloatField(verbose_name='Total Price')),
                ('cashback', models.FloatField(verbose_name='Cashback')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='core.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='core.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
