# Generated by Django 3.2 on 2021-05-14 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, editable=False, verbose_name='Created at')),
                ('modified', models.DateTimeField(db_index=True, verbose_name='Last modified')),
                ('hidden', models.BooleanField(db_index=True, default=False, verbose_name='Hidden or deleted')),
                ('status', models.CharField(choices=[('Waiting for Payment', 'Waiting for Payment'), ('Success', 'Success'), ('Failure', 'Failure')], default='Waiting for Payment', max_length=50, verbose_name='Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='core.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
