# Generated by Django 3.2 on 2021-04-17 17:44

import auth_.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.uploads


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created', models.DateTimeField(db_index=True, editable=False, verbose_name='Created at')),
                ('modified', models.DateTimeField(db_index=True, verbose_name='Last modified')),
                ('hidden', models.BooleanField(db_index=True, default=False, verbose_name='Hidden or deleted')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='User')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email address')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Phone number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Admin', 'Admin'), ('Partner', 'Partner')], default='Customer', max_length=30, verbose_name='Role')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created'],
            },
            managers=[
                ('objects', auth_.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, editable=False, verbose_name='Created at')),
                ('modified', models.DateTimeField(db_index=True, verbose_name='Last modified')),
                ('hidden', models.BooleanField(db_index=True, default=False, verbose_name='Hidden or deleted')),
                ('city', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='City')),
                ('address', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Address')),
                ('birth_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Birth date')),
                ('avatar', models.FileField(blank=True, null=True, upload_to=utils.uploads.avatar_upload, verbose_name='User avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Customer profile',
                'verbose_name_plural': 'Customer profiles',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('customerprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_.customerprofile')),
                ('position', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Work position')),
            ],
            options={
                'verbose_name': 'Admin profile',
                'verbose_name_plural': 'Admin profiles',
            },
            bases=('auth_.customerprofile',),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, editable=False, verbose_name='Created at')),
                ('modified', models.DateTimeField(db_index=True, verbose_name='Last modified')),
                ('hidden', models.BooleanField(db_index=True, default=False, verbose_name='Hidden or deleted')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Brand name')),
                ('logo', models.FileField(blank=True, null=True, upload_to=utils.uploads.brand_logo_upload, verbose_name='Brand logo')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
    ]
