# Generated by Django 3.2 on 2021-04-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Username'),
        ),
    ]
